name: Build and deploy (production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_NAME: website
  CHART_VALUES_FILE: .helm/values.prod.yaml
  DEPLOY_NAMESPACE: podnebnik-prod
  IMAGE_TAG: ${{ github.sha }}
  DEPLOY_ENV: production
  DEPLOY_URL: https://podnebnik.org

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/website:${{ env.IMAGE_TAG}}

  deploy:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'NODEPLOY')"
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: sledilnik/action-helm-deploy@master
        with:
          chartName: sledilnik/django
          chartVersion: '1.0.1'
          kubeconfig: '${{ secrets.KUBECONFIG }}'